apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-tjxn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/qijing/ex-registry-jvhd-tenant/appstudio/dc-metro-map-tjxn@sha256:5bb1817a8e6bc4d1d5c60ce2714f8dc1332c5963038f558070c9a15785fc870c
        name: my-nodejs
        resources: {}
status: {}
