apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-tjxn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-tjxn
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-tjxn
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-tjxn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-tjxn
    spec:
      containers:
      - image: quay.io/qijing/ex-registry-jvhd-tenant/appstudio/dc-metro-map-tjxn@sha256:5bb1817a8e6bc4d1d5c60ce2714f8dc1332c5963038f558070c9a15785fc870c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
